name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: |
          ${{ runner.os }}-pip
    - name: Pre-install
      run: |
        python -m pip install -U pip
    - name: Install package
      run: |
        python -m pip install -e .[test]
    - name: Test
      run: |
        python -m pytest -v -rxXs --cov planet --cov-report term-missing
